# Use root/example as user/password credentials
version: '3.1'

services:
    postgres:
      image: postgres:10.5
      environment:
       - POSTGRES_USER=postgres
       - POSTGRES_PASSWORD=postgres
      ports:
       - '5438:5432'
      volumes:
        - ./postgres-data:/var/lib/postgresql/data

    speed-click-app:
      image: speed-click:latest
      ports:
        - '8085:8080'
      environment:
        DATABASE_URL: jdbc:postgresql://localhost:5432/postgres
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres
      depends_on:
        - postgres

networks:
  prova:
    external: true
